echo Cleaning up old build artifacts...
rm -rf ./dist > /dev/null 2> /dev/null || true
rm -rf /var/www/sarif-frontend > /dev/null 2> /dev/null || true
echo Building sarif_frontend...
npm run vitebuild
echo Removing public artifacts...
rm -rf ./public/index.html ./public/assets/*.css || true
echo Moving public assets to dist...
cp -rf ./public/* dist/
rm -rf ./public || true
mkdir -p /var/www/sarif-frontend
echo Moving dist to /var/www/sarif-frontend...
mv ./dist/* /var/www/sarif-frontend/
echo Done building sarif_frontend.
echo Exiting sarif_frontend docker-entrypoint.sh...
exit 0