services:
  oauth2:
    build: ./
    container_name: sarif_oauth2
    environment:
      - TZ=Europe/Zurich
      - API_KEY
    env_file:
      - .env
    restart: on-failure
    networks:
      - sarifntw
