services:
  oauth2:
    build: ./
    container_name: oauth2
    environment:
      - TZ=Europe/Zurich
      - API_KEY
    env_file:
      - .env
    networks:
      - sarifntw
    volumes:
      - sarif-libs:/libs
    depends_on:
      libs:
        condition: service_completed_successfully
        restart: true
    restart: on-failure
