services:
  usermanager:
    build: ./
    container_name: usermanager
    environment:
      - TZ=Europe/Zurich
      - API_KEY
    env_file:
      - .env
      - ../.env
    networks:
      - sarifntw
    volumes:
      - sarif-libs:/libs/
      - ssl:/ssl
    depends_on:
      libs:
        condition: service_completed_successfully
        restart: true
    restart: on-failure
