services:
  sarif_blockchain:
    container_name: sarif_blockchain
    image: sarif_blockchain
    networks:
      - sarifntw
    build:
      context: ./
      args:
        PROVIDER: ${PROVIDER}
        PRIVATE_KEY: ${PRIVATE_KEY}
    env_file: .env
    environment:
      - API_KEY
    restart: on-failure
