services:
  blockchain:
    container_name: blockchain
    image: sarif_blockchain
    networks:
      - sarifntw
    build:
      context: ./
      args:
        PROVIDER: ${PROVIDER}
        PRIVATE_KEY: ${PRIVATE_KEY}
    env_file: .env
    environment:
      - API_KEY
    restart: on-failure
    depends_on:
      libs:
        condition: service_completed_successfully
        restart: true
