services:
  sarif_blockchain:
    container_name: sarif_blockchain
    networks:
      - sarifntw
    volumes:
      - data:/data
    build: ./
    env_file: .env
    environment:
      - API_KEY
    # depends_on:
    #   - sarif_{DEPENDMODULE}
    # restart: on-failure
