services:
  sarif_blockchain:
    container_name: blockchain_container
    image: sarif_blockchain
    # networks:
    #   - sarifntw
    ports:
      - "8080:8080"
    build:
      context: ./
      args:
        PROVIDER: ${PROVIDER}
        PRIVATE_KEY: ${PRIVATE_KEY}
    env_file: .env
    environment:
      - API_KEY
    # depends_on:
    #   - sarif_{DEPENDMODULE}
    restart: no
