
services:
  sarif_pong_backend:
    build:
     context: ./games/pong
     dockerfile: backend/Dockerfile.backend
    container_name: sarif_pong_backend
    working_dir: /app/backend
    command: npm run dev
    volumes:
      - .games/pong/backend:/app/backend
    ports:
     - "3000:3000"
    depends_on:
      - sarif_pong_frontend
    environment:
      - NODE_ENV=development

  sarif_pong_frontend:
    image: node:23-alpine3.20
    container_name: sarif_pong_frontend
    working_dir: /app/frontend
    command: sh -c "npm install && npm run dev -- --host"
    volumes:
      - ./games/pong/frontend:/app/frontend
      - /app/frontend/node_modules
    ports:
      - "5173:5173"
    networks:
      - sarifntw
    restart: on-failure
    env_file: ../../.env