services:
  sarif_pong:
    container_name: sarif_pong
    networks:
      - sarifntw
    build: ./
    env_file: ../../.env
    environment:
      - API_KEY
    depends_on:
      - sarif_db
    restart: on-failure
