
services:
  sarif_pong_backend:
    build:
     context: .
     dockerfile: ./backend/Dockerfile.backend
    container_name: sarif_pong_backend
    working_dir: /app/backend
    command: npm run dev
    volumes:
      - ./backend:/app/backend
    ports:
     - "1337:1337"
    environment:
      - NODE_ENV=development
