services:
  sarif_pong:
    container_name: sarif_pong
    networks:
      - sarifntw
    build: ./
    env_file: ../../.env
    environment:
      - API_KEY
    restart: on-failure
    volumes:
      - sarif-libs:/libs
