services:
  pong:
    container_name: pong
    networks:
      - sarifntw
    build: ./
    env_file: ../../.env
    environment:
      - API_KEY
    volumes:
      - sarif-libs:/libs
      - ssl:/ssl
    depends_on:
      libs:
        condition: service_completed_successfully
        restart: true
      frontend-builder:
        condition: service_completed_successfully
        restart: true
    restart: on-failure
