# services:
  # sarif_{MODULE}:
  #   container_name: sarif_{MODULE}
  #   networks:
  #     - sarifntw
  #   volumes:
  #     - data:/data
  #   build: ./
  #   env_file: .env
  #   environment:
  #     - API_KEY
  #   depends_on:
  #     - sarif_{DEPENDMODULE}
  #   restart: on-failure
