FROM node:23-alpine3.20 AS builder

WORKDIR /app

COPY	frontend ./frontend
WORKDIR /app/frontend

RUN npm install
RUN npm run build

FROM node:23-alpine3.20

WORKDIR	/app

COPY	backend ./backend
COPY	--from=builder /app/frontend/dist ./frontend/dist

WORKDIR	/app/backend
RUN		npm install

EXPOSE	3000

CMD [ "node", "server.js" ]